site_name: Linspector

#  mkdocs, readthedocs, material, cerulean, cosmo, cyborg, darkly, flatly, journal, litera, lumen, lux, materia, minty, pulse, sandstone, simplex, slate, solar, spacelab, superhero, united, yeti
theme:
  name: readthedocs
  custom_dir: overrides
